databases:
  - name: restaurantedb
    plan: free
    databaseName: restaurante
    user: mysite

services:
  - type: web
    plan: free
    name: restaurante-web
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate && gunicorn proyecto.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: restaurantedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4


